# Generated by Django 5.2.8 on 2025-11-14 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('medecin', 'Médecin'), ('sage_femme', 'Sage-femme'), ('infirmier', 'Infirmier(ère)'), ('pharmacien', 'Pharmacien'), ('agent_enregistrement', "Agent d'enregistrement")], max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MethodeContraceptive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('hormonale', 'Hormonale'), ('barriere', 'Barrière'), ('iud', 'Dispositif intra-utérin (DIU)'), ('permanent', 'Permanent'), ('naturelle', 'Naturelle')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Méthode contraceptive',
                'verbose_name_plural': 'Méthodes contraceptives',
                'db_table': 'methodes_contraceptives',
                'indexes': [models.Index(fields=['categorie'], name='methodes_co_categor_650646_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('antecedents', models.TextField(blank=True, null=True, verbose_name='Antécédents')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'indexes': [models.Index(fields=['nom', 'prenom'], name='patients_nom_d733a3_idx'), models.Index(fields=['telephone'], name='patients_telepho_9a01bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultationPF',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('anamnese', models.TextField(blank=True, null=True, verbose_name='Anamnèse')),
                ('examen', models.TextField(blank=True, null=True, verbose_name='Examen clinique')),
                ('methode_posee', models.BooleanField(default=False, verbose_name='Méthode posée')),
                ('effets_secondaires', models.TextField(blank=True, null=True, verbose_name='Effets secondaires')),
                ('notes', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Professionnel')),
                ('methode_prescite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_prescrites', to='pf.methodecontraceptive', verbose_name='Méthode prescrite')),
                ('methode_proposee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_proposees', to='pf.methodecontraceptive', verbose_name='Méthode proposée')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='pf.patient')),
            ],
            options={
                'verbose_name': 'Consultation PF',
                'verbose_name_plural': 'Consultations PF',
                'db_table': 'consultations_pf',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(blank=True, max_length=200, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pf.consultationpf')),
                ('methode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pf.methodecontraceptive')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='Date et heure')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('absent', 'Absent')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='pf.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL, verbose_name='Professionnel')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'rendez_vous',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité disponible')),
                ('seuil', models.IntegerField(default=10, verbose_name="Seuil d'alerte")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('methode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pf.methodecontraceptive')),
            ],
            options={
                'verbose_name': 'Article de stock',
                'verbose_name_plural': 'Articles de stock',
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('inventaire', 'Inventaire'), ('perte', 'Perte')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pf.stockitem')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvements_stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.AddIndex(
            model_name='consultationpf',
            index=models.Index(fields=['date'], name='consultatio_date_84c806_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationpf',
            index=models.Index(fields=['patient', 'date'], name='consultatio_patient_0b408e_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationpf',
            index=models.Index(fields=['user', 'date'], name='consultatio_user_id_09b294_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='prescriptio_consult_82e09d_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['date_prescription'], name='prescriptio_date_pr_3e1e13_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['datetime'], name='rendez_vous_datetim_e59ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['statut'], name='rendez_vous_statut_b81f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['patient', 'datetime'], name='rendez_vous_patient_517e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['user', 'datetime'], name='rendez_vous_user_id_00debd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['quantite'], name='stock_items_quantit_8bce27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('methode',)},
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date_mouvement'], name='mouvements__date_mo_5995a9_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='mouvements__type_mo_85e8dd_idx'),
        ),
    ]
