# Generated by Django 5.2.8 on 2026-01-05 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('deconnexion', 'Déconnexion')], max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Info appareil')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('date_tentative', models.DateTimeField(auto_now_add=True, verbose_name='Date de tentative')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_connexions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexions',
                'db_table': 'historique_connexions',
                'ordering': ['-date_tentative'],
                'indexes': [models.Index(fields=['user', 'date_tentative'], name='historique__user_id_cea1b7_idx'), models.Index(fields=['statut'], name='historique__statut_b129c3_idx'), models.Index(fields=['ip_address'], name='historique__ip_addr_81c485_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionUtilisateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clé de session')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Info appareil')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_actives', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'db_table': 'sessions_utilisateurs',
                'ordering': ['-derniere_activite'],
                'indexes': [models.Index(fields=['user', 'active'], name='sessions_ut_user_id_01e723_idx'), models.Index(fields=['session_key'], name='sessions_ut_session_ddea74_idx')],
            },
        ),
    ]
