# Generated by Django 5.2.8 on 2025-11-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='Hôpital Abass Ndao', max_length=200, verbose_name='Texte du logo')),
                ('hero_title', models.CharField(default="Bienvenue à l'Hôpital Abass Ndao", max_length=200, verbose_name='Titre principal')),
                ('hero_description', models.TextField(default='Votre partenaire de confiance pour la santé et le bien-être.', verbose_name='Description hero')),
                ('hero_button_primary', models.CharField(default="Accéder à l'application", max_length=100, verbose_name='Bouton principal')),
                ('hero_button_secondary', models.CharField(default='En savoir plus', max_length=100, verbose_name='Bouton secondaire')),
                ('about_title', models.CharField(default="À propos de l'Hôpital Abass Ndao", max_length=200, verbose_name='Titre section à propos')),
                ('about_description_1', models.TextField(verbose_name='Description 1')),
                ('about_description_2', models.TextField(verbose_name='Description 2')),
                ('about_stat_1_value', models.CharField(default='15+', max_length=50, verbose_name='Statistique 1 - Valeur')),
                ('about_stat_1_label', models.CharField(default="Années d'expérience", max_length=100, verbose_name='Statistique 1 - Label')),
                ('about_stat_2_value', models.CharField(default='50+', max_length=50, verbose_name='Statistique 2 - Valeur')),
                ('about_stat_2_label', models.CharField(default='Professionnels', max_length=100, verbose_name='Statistique 2 - Label')),
                ('services_title', models.CharField(default='Nos Services', max_length=200, verbose_name='Titre section services')),
                ('services_subtitle', models.TextField(default='Nous offrons une gamme complète de services médicaux', verbose_name='Sous-titre services')),
                ('values_title', models.CharField(default='Pourquoi nous choisir ?', max_length=200, verbose_name='Titre section valeurs')),
                ('values_subtitle', models.TextField(default='Des valeurs qui font la différence dans nos soins', verbose_name='Sous-titre valeurs')),
                ('footer_about_text', models.TextField(default='Votre partenaire de confiance pour la santé et le bien-être de la communauté.', verbose_name='Texte footer à propos')),
                ('footer_address', models.CharField(default='Abass Ndao, Dakar, Sénégal', max_length=200, verbose_name='Adresse')),
                ('footer_phone', models.CharField(default='+221 33 XXX XX XX', max_length=50, verbose_name='Téléphone')),
                ('footer_email', models.EmailField(default='contact@abassndao.sn', max_length=254, verbose_name='Email')),
                ('footer_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('footer_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('footer_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('footer_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Contenu de la page d'accueil",
                'verbose_name_plural': "Contenu de la page d'accueil",
                'db_table': 'landing_page_content',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.CharField(default='Heart', max_length=100, verbose_name="Nom de l'icône Lucide")),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pf.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.CharField(default='Shield', max_length=100, verbose_name="Nom de l'icône Lucide")),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='pf.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Valeur',
                'verbose_name_plural': 'Valeurs',
                'db_table': 'values',
                'ordering': ['ordre'],
            },
        ),
    ]
