# Generated by Django 5.2.8 on 2026-01-07 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0002_historiqueconnexion_sessionutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentePharmacie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_vente', models.CharField(max_length=50, unique=True)),
                ('nom_client', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('telephone_client', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_rendu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile', 'Paiement mobile'), ('cheque', 'Chèque'), ('credit', 'Crédit')], default='especes', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='ventes/prescriptions/')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de vente')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='pf.pharmacie')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente Pharmacie',
                'verbose_name_plural': 'Ventes Pharmacies',
                'db_table': 'ventes_pharmacies',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remise_montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ventes', to='pf.produit')),
                ('stock_produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ventes', to='pf.stockproduit', verbose_name='Stock utilisé')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pf.ventepharmacie')),
            ],
            options={
                'verbose_name': 'Ligne Vente',
                'verbose_name_plural': 'Lignes Ventes',
                'db_table': 'lignes_ventes',
            },
        ),
        migrations.AddIndex(
            model_name='ventepharmacie',
            index=models.Index(fields=['numero_vente'], name='ventes_phar_numero__02bb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='ventepharmacie',
            index=models.Index(fields=['pharmacie', 'date_vente'], name='ventes_phar_pharmac_16a21a_idx'),
        ),
        migrations.AddIndex(
            model_name='ventepharmacie',
            index=models.Index(fields=['vendeur', 'date_vente'], name='ventes_phar_vendeur_89ac58_idx'),
        ),
        migrations.AddIndex(
            model_name='ventepharmacie',
            index=models.Index(fields=['mode_paiement'], name='ventes_phar_mode_pa_e1e4ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lignevente',
            unique_together={('vente', 'produit')},
        ),
    ]
