# Generated by Django 5.2.8 on 2026-01-08 01:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0003_ventepharmacie_lignevente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_hopital', 'Administrateur Hôpital'), ('specialiste', 'Spécialiste'), ('pharmacien', 'Pharmacien'), ('employe_pharmacie', 'Employé Pharmacie'), ('agent_enregistrement', "Agent d'enregistrement"), ('patient', 'Patient')], max_length=30),
        ),
        migrations.CreateModel(
            name='EmployePharmacie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('poste', models.CharField(default='Employé', max_length=100, verbose_name='Poste')),
                ('date_embauche', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche")),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire')),
                ('peut_vendre', models.BooleanField(default=True, verbose_name='Peut effectuer des ventes')),
                ('peut_gerer_stock', models.BooleanField(default=False, verbose_name='Peut gérer le stock')),
                ('peut_voir_commandes', models.BooleanField(default=True, verbose_name='Peut voir les commandes')),
                ('peut_traiter_commandes', models.BooleanField(default=False, verbose_name='Peut traiter les commandes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='pf.pharmacie', verbose_name='Pharmacie')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'employe_pharmacie'}, on_delete=django.db.models.deletion.CASCADE, related_name='employe_pharmacie', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé Pharmacie',
                'verbose_name_plural': 'Employés Pharmacies',
                'db_table': 'employes_pharmacies',
                'ordering': ['user__nom'],
                'indexes': [models.Index(fields=['pharmacie'], name='employes_ph_pharmac_7bacf8_idx'), models.Index(fields=['user'], name='employes_ph_user_id_23119e_idx'), models.Index(fields=['actif'], name='employes_ph_actif_a5904c_idx')],
                'unique_together': {('user', 'pharmacie')},
            },
        ),
    ]
