# Generated by Django 5.2.8 on 2025-11-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0003_patient_email_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'db_table': 'contact_messages',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterModelOptions(
            name='methodecontraceptive',
            options={'ordering': ['nom'], 'verbose_name': 'Méthode contraceptive', 'verbose_name_plural': 'Méthodes contraceptives'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date_prescription'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.RemoveIndex(
            model_name='methodecontraceptive',
            name='methodes_co_categor_650646_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_consult_82e09d_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_date_pr_3e1e13_idx',
        ),
        migrations.RemoveIndex(
            model_name='rendezvous',
            name='rendez_vous_user_id_00debd_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_items_quantit_8bce27_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='methodecontraceptive',
            name='categorie',
            field=models.CharField(choices=[('hormonale', 'Hormonale'), ('barriere', 'Barrière'), ('iud', 'DIU'), ('permanent', 'Permanent'), ('naturelle', 'Naturelle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='methode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pf.methodecontraceptive'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='methode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pf.methodecontraceptive'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='patients_email_bf0efb_idx'),
        ),
        migrations.AlterModelTable(
            name='stockitem',
            table='stocks',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_contact', to='pf.patient', verbose_name='Patient'),
        ),
    ]
