# Generated by Django 5.2.8 on 2026-01-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0004_alter_user_role_employepharmacie'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ethnie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ethnie'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_cne',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro CNE'),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro CNI'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du patient')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom du patient')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('age', models.IntegerField(verbose_name='Âge')),
                ('residence', models.CharField(max_length=200, verbose_name='Résidence')),
                ('ethnie', models.CharField(max_length=100, verbose_name='Ethnie')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('numero_cni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNI')),
                ('numero_cne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNE')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('consultation_nc', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10, verbose_name='NC')),
                ('consultation_ac', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10, verbose_name='AC')),
                ('consultation_refere_asc', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10, verbose_name='REFERE ASC')),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('taille_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taille (cm)')),
                ('poids_taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids/Taille')),
                ('taille_age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille/Âge')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('motif_symptomes', models.TextField(verbose_name='Motif ou symptômes')),
                ('examen_labo_type', models.CharField(choices=[('negatif', 'Négatif'), ('positif', 'Positif')], max_length=20, verbose_name='Type examen labo')),
                ('diagnostic', models.TextField(verbose_name='Diagnostic')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registres', to='pf.hopital', verbose_name='Hôpital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres', to='pf.patient', verbose_name='Patient lié')),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registres', to='pf.specialiste', verbose_name='Spécialiste')),
            ],
            options={
                'verbose_name': 'Registre',
                'verbose_name_plural': 'Registres',
                'db_table': 'registres',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['hopital', 'specialiste'], name='registres_hopital_d3f1e7_idx'), models.Index(fields=['patient'], name='registres_patient_d86c69_idx'), models.Index(fields=['date_creation'], name='registres_date_cr_564348_idx'), models.Index(fields=['numero_cni'], name='registres_numero__3c1104_idx'), models.Index(fields=['numero_cne'], name='registres_numero__b9f6d9_idx'), models.Index(fields=['actif'], name='registres_actif_8c2634_idx')],
            },
        ),
    ]
