# Generated by Django 5.2.8 on 2026-01-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0005_patient_ethnie_patient_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_ordonnance', models.CharField(max_length=50, unique=True)),
                ('patient_nom', models.CharField(max_length=100, verbose_name='Nom du patient')),
                ('patient_prenom', models.CharField(max_length=100, verbose_name='Prénom du patient')),
                ('patient_age', models.IntegerField(verbose_name='Âge du patient')),
                ('patient_sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('diagnostic', models.TextField(verbose_name='Diagnostic')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('recommandations', models.TextField(blank=True, null=True, verbose_name='Recommandations')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('delivree', 'Délivrée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('date_prescription', models.DateTimeField(auto_now_add=True, verbose_name='Date de prescription')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_delivrance', models.DateTimeField(blank=True, null=True, verbose_name='Date de délivrance')),
                ('duree_validite_jours', models.IntegerField(default=30, verbose_name='Durée de validité (jours)')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='pf.hopital', verbose_name='Hôpital')),
                ('pharmacie_delivrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_delivrees', to='pf.pharmacie', verbose_name='Pharmacie de délivrance')),
                ('registre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='pf.registre', verbose_name='Registre')),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='pf.specialiste', verbose_name='Spécialiste prescripteur')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'db_table': 'ordonnances',
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_medicament', models.CharField(blank=True, max_length=200, verbose_name='Nom du médicament (si non référencé)')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantité')),
                ('unite', models.CharField(choices=[('comprime', 'Comprimé(s)'), ('gelule', 'Gélule(s)'), ('ml', 'ml'), ('mg', 'mg'), ('g', 'g'), ('sachet', 'Sachet(s)'), ('ampoule', 'Ampoule(s)'), ('suppositoire', 'Suppositoire(s)'), ('application', 'Application(s)'), ('goutte', 'Goutte(s)'), ('autre', 'Autre')], max_length=20, verbose_name='Unité')),
                ('frequence', models.CharField(choices=[('1_fois_jour', '1 fois par jour'), ('2_fois_jour', '2 fois par jour'), ('3_fois_jour', '3 fois par jour'), ('4_fois_jour', '4 fois par jour'), ('matin', 'Le matin'), ('midi', 'À midi'), ('soir', 'Le soir'), ('coucher', 'Au coucher'), ('si_besoin', 'Si besoin'), ('autre', 'Autre')], max_length=20, verbose_name='Fréquence')),
                ('frequence_detail', models.CharField(blank=True, max_length=200, verbose_name='Détail fréquence')),
                ('moment_prise', models.CharField(choices=[('avant_repas', 'Avant les repas'), ('pendant_repas', 'Pendant les repas'), ('apres_repas', 'Après les repas'), ('jeun', 'À jeun'), ('coucher', 'Au coucher'), ('si_besoin', 'Si besoin'), ('autre', 'Autre')], max_length=20, verbose_name='Moment de prise')),
                ('duree_traitement', models.IntegerField(verbose_name='Durée du traitement (jours)')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('quantite_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité totale à délivrer')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ordonnances', to='pf.produit', verbose_name='Médicament/Produit')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pf.ordonnance', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnances",
                'db_table': 'lignes_ordonnances',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['numero_ordonnance'], name='ordonnances_numero__38138c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['registre'], name='ordonnances_registr_cfed96_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['specialiste', 'date_prescription'], name='ordonnances_special_6030c3_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['statut'], name='ordonnances_statut_cea8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['date_expiration'], name='ordonnances_date_ex_19762e_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneordonnance',
            index=models.Index(fields=['ordonnance', 'ordre'], name='lignes_ordo_ordonna_ae303a_idx'),
        ),
    ]
