# Generated by Django 5.2.8 on 2026-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0006_ordonnance_ligneordonnance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='ordonnances/qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL du QR Code'),
        ),
    ]
