# Generated by Django 5.2.8 on 2026-01-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0007_ordonnance_qr_code_ordonnance_qr_code_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(max_length=50, unique=True)),
                ('patient_nom', models.CharField(max_length=100, verbose_name='Nom du patient')),
                ('patient_prenom', models.CharField(max_length=100, verbose_name='Prénom du patient')),
                ('patient_age', models.IntegerField(verbose_name='Âge du patient')),
                ('patient_sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('motif_consultation', models.TextField(verbose_name='Motif de consultation')),
                ('histoire_maladie', models.TextField(verbose_name='Histoire de la maladie')),
                ('antecedents', models.TextField(blank=True, null=True, verbose_name='Antécédents')),
                ('antecedents_familiaux', models.TextField(blank=True, null=True, verbose_name='Antécédents familiaux')),
                ('gyneco_obstetricaux', models.TextField(blank=True, null=True, verbose_name='Gynéco-Obstétricaux')),
                ('chirurgicaux', models.TextField(blank=True, null=True, verbose_name='Chirurgicaux')),
                ('examen_general', models.TextField(blank=True, null=True, verbose_name='Examen général')),
                ('examen_physique', models.TextField(blank=True, null=True, verbose_name='Examen physique')),
                ('hypothese_diagnostic', models.TextField(blank=True, null=True, verbose_name='Hypothèse diagnostic')),
                ('diagnostic', models.TextField(blank=True, null=True, verbose_name='Diagnostic')),
                ('bilan_biologie', models.TextField(blank=True, null=True, verbose_name='Bilan - Biologie')),
                ('bilan_imagerie', models.TextField(blank=True, null=True, verbose_name='Bilan - Imagerie')),
                ('date_consultation', models.DateTimeField(auto_now_add=True, verbose_name='Date de consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_medicaux', to='pf.hopital', verbose_name='Hôpital')),
                ('registre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_medicaux', to='pf.registre', verbose_name='Registre')),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_medicaux', to='pf.specialiste', verbose_name='Spécialiste')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
                'db_table': 'dossiers_medicaux',
                'ordering': ['-date_consultation'],
                'indexes': [models.Index(fields=['numero_dossier'], name='dossiers_me_numero__a87310_idx'), models.Index(fields=['registre'], name='dossiers_me_registr_729522_idx'), models.Index(fields=['specialiste', 'date_consultation'], name='dossiers_me_special_c5f2d9_idx')],
            },
        ),
    ]
