# Generated by Django 5.2.8 on 2026-02-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0008_dossiermedical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationpf',
            name='methode_prescite',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='methode',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='methode_contraceptive',
        ),
        migrations.RemoveField(
            model_name='consultationpf',
            name='methode_proposee',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='methode',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='commandepharmacie',
            name='prescription',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='pharmacie',
        ),
        migrations.CreateModel(
            name='FichierDossierMedical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_fichier', models.CharField(choices=[('gyneco_obstetricaux', 'Gynéco-Obstétricaux'), ('chirurgicaux', 'Chirurgicaux'), ('examen_general', 'Examen général'), ('examen_physique', 'Examen physique'), ('hypothese_diagnostic', 'Hypothèse diagnostic'), ('diagnostic', 'Diagnostic'), ('biologie', 'Biologie'), ('imagerie', 'Imagerie'), ('autre', 'Autre')], max_length=50, verbose_name='Type de fichier')),
                ('fichier', models.FileField(upload_to='dossiers_medicaux/%Y/%m/%d/', verbose_name='Fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('taille_fichier', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (octets)')),
                ('type_mime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='pf.dossiermedical', verbose_name='Dossier médical')),
            ],
            options={
                'verbose_name': 'Fichier de dossier médical',
                'verbose_name_plural': 'Fichiers de dossiers médicaux',
                'db_table': 'fichiers_dossiers_medicaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MethodeContraceptive',
        ),
        migrations.DeleteModel(
            name='MouvementStock',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.AddIndex(
            model_name='fichierdossiermedical',
            index=models.Index(fields=['dossier_medical', 'type_fichier'], name='fichiers_do_dossier_df9ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='fichierdossiermedical',
            index=models.Index(fields=['created_at'], name='fichiers_do_created_d94269_idx'),
        ),
    ]
