// Management Pages exports
export { Hopitaux } from './Hopitaux'
export { HopitalDetail } from './HopitalDetail'
export { Pharmacies } from './Pharmacies'
export { PharmacieDetail } from './PharmacieDetail'
export { Patients } from './Patients'
export { PatientDetail } from './PatientDetail'
export { Consultations } from './Consultations'
export { ConsultationDetail } from './ConsultationDetail'
export { RendezVous } from './RendezVous'
export { RendezVousDetail } from './RendezVousDetail'
export { Stocks } from './Stocks'
export { Utilisateurs } from './Utilisateurs'
export { Fournisseurs } from './Fournisseurs'
export { default as Parametres } from './Parametres'